const peopleList = [
  {
    email: 'gingras@lunenfeld.ca',
    file: 'anneclaude-gingras',
    name: 'Anne-Claude Gingras',
    title: 'Principal investigator',
    group: 'Principal investigator',
    blurb: '',
  },
  {
    email: 'colwill@lunenfeld.ca',
    file: 'karen-colwill',
    name: 'Karen Colwill',
    title: 'Manager, NBCC',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'hesketh@lunenfeld.ca',
    file: 'geoffrey-hesketh',
    name: 'Geoffrey Hesketh',
    title: 'Scientific associate',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'rkalloush@lunenfeld.ca',
    file: 'rawan-kalloush',
    name: 'Rawan Kalloush',
    title: 'Lab manager',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'bseale@lunenfeld.ca',
    file: 'brendon-seale',
    name: 'Brendon  Seale',
    title: 'Scientific associate',
    group: 'Staff',
    blurb: '',
  },  
  {
    email: 'cwong@lunenfeld.ca',
    file: 'cassandra-wong',
    name: 'Cassandra Wong',
    title: 'Mass spectrometry technician',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'zlin@lunenfeld.ca',
    file: 'zhenyuan-lin',
    name: 'Zhen-Yuan Lin',
    title: 'Research technician',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'bkhatri@lunenfeld.ca',
    file: 'bhavisha-rathod',
    name: 'Bhavisha Rathod',
    title: 'Research technician',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'whardy@lunenfeld.ca',
    file: 'rod-hardy',
    name: 'Rod Hardy',
    title: 'CoVaRR-Net research associate',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'qhu@lunenfeld.ca',
    file: 'queenie-hu',
    name: 'Queenie Hu',
    title: 'Research associate',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'lseifried@lunenfeld.ca',
    file: 'laurie-seifried',
    name: 'Laurie Seifried',
    title: 'CoVaRR-Net pillar coordinator',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'fqi@lunenfeld.ca',
    file: '',
    name: 'Freda Qi',
    title: 'Bioinformatics specialist',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'vmacwan@lunenfeld.ca',
    file: '',
    name: 'Vinitha Macwan',
    title: 'Reseach Technician',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'vanipindi@lunenfeld.ca',
    file: '',
    name: 'Varun Anipindi',
    title: 'Project Manager',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'gliu@lunenfeld.ca',
    file: 'frank-liu',
    name: 'Frank Liu',
    title: 'Programmer',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'jpzhang@lunenfeld.ca',
    file: 'jianping-zhang',
    name: 'Jian-Ping Zhang',
    title: 'Programmer',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'boliu@lunenfeld.ca',
    file: 'bob-liu',
    name: 'Bob Liu',
    title: 'Programmer',
    group: 'Staff',
    blurb: '',
  },
  {
    email: 'udionne@lunenfeld.ca',
    file: 'ugo-dionne',
    name: 'Ugo Dionne',
    title: 'Postdoctoral fellow',
    group: 'Postdoctoral fellow',
    blurb: '',
  },
  {
    email: 'calvinchan@lunenfeld.ca',
    file: 'calvin-chan',
    name: 'Calvin Chan',
    title: 'Postdoctoral fellow',
    group: 'Postdoctoral fellow',
    blurb: '',
  },
  {
    email: 'ralmismar@lunenfeld.ca',
    file: 'rasha-mismar',
    name: 'Rasha Al Mismar',
    title: 'Postdoctoral fellow',
    group: 'Postdoctoral fellow',
    blurb: '',
  },
  {
    email: 'rsamson@lunenfeld.ca',
    file: 'reuben-samson',
    name: 'Reuben Samson',
    title: 'Postdoctoral fellow',
    group: 'Postdoctoral fellow',
    blurb: '',
  },
  {
    email: 'bdyakov@lunenfeld.ca',
    file: 'boris-dyakov',
    name: 'Boris Dyakov',
    title: 'Graduate student',
    group: 'Student',
    blurb: '',
  },
  {
    email: 'shimon.rosenthal@mail.utoronto.ca',
    file: 'shimon-rosenthal',
    name: 'Shimon Rosenthal',
    title: 'Graduate student',
    group: 'Student',
    blurb: '',
  },
  {
    email: 'fzangari@lunenfeld.ca',
    file: 'francesco-zangari',
    name: 'Francesco Zangari',
    title: 'Graduate student',
    group: 'Student',
    blurb: '',
  },
  {
    email: 'jkitaygorodsky@lunenfeld.ca',
    file: 'julia-kitaygorodsky',
    name: 'Julia Kitaygorodsky',
    title: 'Graduate student',
    group: 'Student',
    blurb: '',
  },
  {
    email: 'bmohamed@lunenfeld.ca',
    file: '',
    name: 'Bilan Mohamed',
    title: 'Graduate student',
    group: 'Student',
    blurb: '',
  },
  {
    email: 'saya.sedighi@lunenfeld.ca',
    file: 'saya-sedighi',
    name: 'Saya Sedighi',
    title: 'Graduate student',
    group: 'Student',
    blurb: '',
  },
  {
    email: 'vesal.kasmaeifar@mail.utoronto.ca',
    file: 'vesal-kasmaeifar',
    name: 'Vesal Kasmaeifar',
    title: 'Graduate student',
    group: 'Student',
    blurb: '',
  },
  {
    email: 'kosar.vafaee@mail.utoronto.ca',
    file: 'kosar-vafaee',
    name: 'Kosar Vafaee',
    title: 'Graduate Student',
    group: 'Student',
    blurb: '',
  },
  {
    email: 'sguo@lunenfeld.ca',
    file: '',
    name: 'Shuyue Guo',
    title: 'Graduate Student',
    group: 'Student',
    blurb: '',
  },
  {
    email: 'ahong@lunenfeld.ca',
    file: 'agnes-hong',
    name: 'Agnes Hong',
    title: 'Graduate Student',
    group: 'Student',
    blurb: '',
  },
];

export default peopleList;
